site_name: SingleID Document
site_url: https://docs.singleid.jp/

#theme:
#  name: readthedocs
#  include_homepage_in_sidebar: false
#  locale: ja

theme:
  name: material
  language: ja
  palette: 
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

extra:
  generator: false

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang: ja

copyright: Copyright &copy; 2021 - 2022 SingleID K.K.

nav:
  - HOME: index.md
  - SingleID管理者ガイド:
    - はじめに: singleid-adminguide/index.md
    - ユーザ: singleid-adminguide/user.md
    - グループ: singleid-adminguide/group.md
    - 認証:
      - LDAP: singleid-adminguide/ldap.md
      - RADIUS: singleid-adminguide/radius.md
      - 証明書: singleid-adminguide/pki.md
      - アプリ連携: singleid-adminguide/app_integration.md
    - 管理:
      - 基本情報（組織アカウント）: singleid-adminguide/accountinfo.md
      - 管理者: singleid-adminguide/admin.md
      - 詳細設定: singleid-adminguide/setting.md
    - サポート: singleid-adminguide/support.md
  - SingleIDユーザガイド:
    - はじめに: singleid-userguide/index.md
