name: publish

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs mkdocs-material fontawesome_markdown
      - run: echo "pubdocs.singleid.jp" > docs/CNAME
      - run: mkdocs gh-deploy --force